### PR TITLE
Data inconsistency breaking island creation fix and performance improvements

### PR DESCRIPTION
**Pull request by Slind14**
I would be glad if you could consider merging this and building upon it, because it would make it a lot easier to gain from further development on both sides. 

## Resolves
1. a claim UUID changed (I don't know how) this broke the "isTaken" check
2. claims disappeared (3 islands without claims) this broke the island creation again
3. claims existed without islands, this broke the island creation again as the pattern length is based on existing islands.(edited)
4. island creation causing lag spikes, when it scanned for available spots, hence I replaced the loop with a hashSet and contains call
5. lag spike on world save due to island save (islands are saved on change, this also reflects GP claim creation save)
6. fix island creation on claim resize
7. fix island spawn after reset

## Important
The migration is not fully automated. I did half of it manually. Meaning the database schema update needs to be done by hand or added.
In the case of a claim being an unoccupied region, the conflicting claim is being removed.
Once GP supports the creation of claims without an online player, I would recommend to create a new claim in the instance of it being missing. A todo comment is already in place for it.

## Tested
We have been using these changes _(besides the latest merge from upstream)_ since their commits on our live server with an average of 25 players online and hundreds of islands. Since then we did not have any further issues with not being able to create islands and no other issues (besides the solved ones) haven been reported so far.

### CODE REVIEW

**Comment by Mohron** [comment]
Unfortunately your fork is incompatible with our bleeding branch which has many significant improvements over what's currently in dev. The change to the DB schema is not one we will be implementing before making our own changes to enable awesome new features. You will need to prepare your own migration code once you are ready to update GP and SkyClaims. Sorry

**Comment by Slind14** [comment]
I understand, I won't trouble you with any further pull request and just go my way until you reach a production ready state.

**Comment by Mohron** [comment]
@Slind14 Your contributions aren't any trouble! We appreciate what you've done for us so far. Your input is highly valued especially with your large user base. I went over the differences of your dev branch and ours and I believe we've addressed every issue you address in your fork in bleeding. I hope you will be highly satisfied with our bleeding release that should be out this weekend.

**Comment by Slind14** [comment]
I just don't like wasting time. I see you fixing issues which I fixed days ago, using the same or similar approach. e.g. https://github.com/Mohron/SkyClaims/commit/f44eb7907889aa0bb118b30190fea24b1b4dec94 and there are still some of those issues unfixed. 
Using the original version of the plugin isn't possible because it is not production ready and merging your new features is a lot of continue work and gets more tedious with every commit.

So the best approach for me is to just let you do your thing, until you guys have a production ready and well performing state and use the custom build which has been running without issues for days with thousands of islands.

**Pull request closed without merging**
