### PR TITLE
fix some problem in commands & welcome page

### PR DESCRIPTION
**Pull request by subtank**
fix some problem in commands & welcome page

### CODE REVIEW

**Comment by phit** [comment]
this is the right format for wiki images

```
[![Discord](/SkyClaims/_images/Discord.png)](https://discord.gg/EkVQycV)
| [![Patreon](/SkyClaims/_images/Patreon.png)](https://www.patreon.com/mohron)
| [![PayPal](/SkyClaims/_images/Paypal.png)](https://www.paypal.me/mohron)
```

**Comment by subtank** [comment]
@phit in chinese page it must use the absoult link to show the png

**Comment by phit** [comment]
what I wrote is the absolute link minus the domain, you are still linking to the old images..

**Comment by subtank** [comment]
but i try many times your link didn't work.

**Comment by phit** [comment]
they do, just not in the preview on github, but they will work on the actual wiki page once this is merged

**Comment by subtank** [comment]
well

**Pull request merged**
