### PR TITLE
Void World Generation

### PR DESCRIPTION
**Pull request by Mohron**
This will add Void world generation capabilities to SkyClaims.
It will also include optional optimizations for the Nether.

### CODE REVIEW

**Comment by Mohron** [comment]
https://github.com/SpongePowered/SpongeCommon/issues/1506

**Comment by PurpleIsEverything** [comment]
Is this not being merged? The upstream changes in Sponge have been made.

**Comment by Mohron** [comment]
I do want to merge it but to my schematic branch so I need time to update it. I've been extremely busy lately

**Comment by PurpleIsEverything** [comment]
Alright, we've been using sponge's void world generation type with Skyclaims and we have noticed that sometimes islands don't generate. I was looking for an alternative.

**Comment by Mohron** [comment]
@PurpleIsEverything if you're willing to try it out, I have a test build for you.  I haven't had time to test it myself, I just ported over the code from this PR.

**Comment by Mohron** [comment]
Was merged here: b73a2964031d3ff3e1757f64d63eb8d87a33f85a

Will not be merged into API 5

**Pull request closed without merging**
